INSERT INTO ingredients (name, category, serving_size, unit, calories, protein, fiber, starch, sugar, saturated_fat, monounsat_fat, polyunsat_fat, trans_fat, cholesterol) VALUES
  ('egg (whole)', 'protein', 50, 'g', 63, 16.4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('onion', 'vegetables', 150, 'g', 40, 1.1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('bell pepper', 'vegetables', 120, 'g', 26, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('potato', 'vegetables', 150, 'g', 77, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('tomato', 'vegetables', 150, 'g', 18, 0.9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('carrot', 'vegetables', 120, 'g', 41, 0.9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('green onion', 'vegetables', 15, 'g', 32, 1.8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('garlic', 'vegetables', 10, 'g', 149, 6.4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('pork belly', 'protein', 100, 'g', 518, 9.3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('pork ribs', 'protein', 150, 'g', 277, 18, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('pork shoulder', 'protein', 120, 'g', 231, 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('ground beef', 'protein', 100, 'g', 254, 26, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('ribeye steak', 'protein', 150, 'g', 291, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('sirloin steak', 'protein', 150, 'g', 206, 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('flank steak', 'protein', 120, 'g', 192, 28, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('chicken breast', 'protein', 150, 'g', 165, 31, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('chicken thigh', 'protein', 120, 'g', 209, 26, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('chicken wing', 'protein', 100, 'g', 203, 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('chicken drumstick', 'protein', 100, 'g', 172, 28, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('white rice', 'grains', 150, 'g', 130, 2.7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('brown rice', 'grains', 150, 'g', 112, 2.6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('pasta', 'grains', 100, 'g', 131, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('oats', 'grains', 40, 'g', 389, 16.9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('milk', 'dairy', 240, 'ml', 42, 3.4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('cheddar cheese', 'dairy', 30, 'g', 403, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('mozzarella cheese', 'dairy', 30, 'g', 300, 22, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('parmesan cheese', 'dairy', 15, 'g', 431, 38, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('butter', 'fats', 15, 'g', 717, 0.9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('olive oil', 'fats', 15, 'ml', 884, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('vegetable oil', 'fats', 15, 'ml', 884, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('coconut oil', 'fats', 15, 'ml', 862, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('sesame oil', 'fats', 5, 'ml', 884, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('apple', 'fruits', 180, 'g', 52, 0.3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('banana', 'fruits', 120, 'g', 89, 1.1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('orange', 'fruits', 150, 'g', 47, 0.9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('strawberry', 'fruits', 150, 'g', 32, 0.7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('blueberry', 'fruits', 150, 'g', 57, 0.7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('lemon', 'fruits', 60, 'g', 29, 1.1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('salmon', 'protein', 150, 'g', 208, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('tuna', 'protein', 150, 'g', 144, 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('shrimp', 'protein', 100, 'g', 99, 24, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('cod', 'protein', 150, 'g', 105, 23, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('soy sauce', 'condiment', 15, 'ml', 8, 1.3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('gochujang', 'condiment', 15, 'g', 243, 5.1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('honey', 'condiment', 20, 'g', 304, 0.3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('mayonnaise', 'condiment', 15, 'g', 680, 1.2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('udon noodles', 'grains', 200, 'g', 99, 2.6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('ramen noodles', 'grains', 150, 'g', 138, 4.4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('cucumber', 'vegetables', 100, 'g', 15, 0.7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('jalapeños', 'vegetables', 20, 'g', 29, 0.9, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('enoki mushrooms', 'vegetables', 100, 'g', 24, 2.7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('shiitake mushrooms', 'vegetables', 100, 'g', 34, 2.2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('peanut butter', 'fats', 30, 'g', 588, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('lao gan ma', 'condiment', 15, 'g', 320, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('flour', 'grains', 125, 'g', 364, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('sriracha sauce', 'condiment', 15, 'ml', 17, 0.2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('roll buns', 'grains', 60, 'g', 250, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('dill pickles', 'vegetables', 30, 'g', 11, 0.3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('green olives', 'vegetables', 30, 'g', 115, 0.8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('rice cakes', 'grains', 20, 'g', 387, 7.3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('miso sauce', 'condiment', 15, 'g', 199, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('kimchi', 'vegetables', 50, 'g', 15, 1.1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('shrimp sauce', 'condiment', 10, 'ml', 35, 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('gochugaru', 'condiment', 5, 'g', 282, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('clams', 'protein', 100, 'g', 148, 26, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('mussels', 'protein', 100, 'g', 172, 24, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('sausages', 'protein', 100, 'g', 301, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('firm tofu', 'protein', 100, 'g', 144, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('silken tofu', 'protein', 100, 'g', 55, 4.8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('egg whites', 'protein', 60, 'ml', 52, 11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('egg yolks', 'protein', 20, 'g', 322, 16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('white wine', 'alcohol', 150, 'ml', 82, 0.1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('red wine', 'alcohol', 150, 'ml', 85, 0.1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
