INSERT INTO nutrients (name, unit, category) VALUES
  ('Vitamin A (Retinol)', 'µg', 'vitamin'),
  ('Vitamin B1 (Thiamine)', 'mg', 'vitamin'),
  ('Vitamin B2 (Riboflavin)', 'mg', 'vitamin'),
  ('Vitamin B3 (Niacin)', 'mg', 'vitamin'),
  ('Vitamin B5 (Pantothenic Acid)', 'mg', 'vitamin'),
  ('Vitamin B6 (Pyridoxine)', 'mg', 'vitamin'),
  ('Vitamin B7 (Biotin)', 'µg', 'vitamin'),
  ('Vitamin B9 (Folate)', 'µg', 'vitamin'),
  ('Vitamin B12 (Cobalamin)', 'µg', 'vitamin'),
  ('Choline', 'mg', 'vitamin'),
  ('Vitamin C (Ascorbic Acid)', 'mg', 'vitamin'),
  ('Vitamin D (Calciferol)', 'µg', 'vitamin'),
  ('Vitamin E (Tocopherol)', 'mg', 'vitamin'),
  ('Vitamin K (Phylloquinone)', 'µg', 'vitamin'),
  ('Calcium', 'mg', 'mineral'),
  ('Chloride', 'mg', 'mineral'),
  ('Chromium', 'µg', 'mineral'),
  ('Copper', 'mg', 'mineral'),
  ('Iodine', 'µg', 'mineral'),
  ('Iron', 'mg', 'mineral'),
  ('Magnesium', 'mg', 'mineral'),
  ('Manganese', 'mg', 'mineral'),
  ('Molybdenum', 'µg', 'mineral'),
  ('Phosphorus', 'mg', 'mineral'),
  ('Potassium', 'mg', 'mineral'),
  ('Selenium', 'µg', 'mineral'),
  ('Sodium', 'mg', 'mineral'),
  ('Sulfur', 'mg', 'mineral'),
  ('Zinc', 'mg', 'mineral')
;
